MyFirstMvcApp/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyFirstMvcApp.Model;
using MyFirstMvcApp.Services;

namespace MyFirstMvcApp.Controllers
{
    public class CourseController : Controller
    {
        //private readonly ILogger<TeacherController> _logger;
        //private readonly StudentDbContext _context;
        private readonly ICourseService _courseService;
        private readonly ITimeService _timeService;
        public CourseController(ICourseService service,ITimeService timeService)
        {
            _courseService = service;
            _timeService = timeService;

        }
        public async Task<IActionResult> Index()
        {
            List<Course> teachers = new List<Course>();
            teachers = await _courseService.GetAllCoursesAsync();
            TempData["message"] = $"Controller Time :{ _timeService.GetCurrentTime()}, service time :{await _courseService.GetDateTime()}";
            return View(teachers);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.User = "Binod";
            var teacher = new Course() { CourseName = "" };
            return View(teacher);
        }
        [HttpPost]
        public async Task<IActionResult> Create(Course model)
        {
            if (ModelState.IsValid)
            {
                await _courseService.CreateCourseAsync(model);
                TempData["message"] = $"{model.CourseName} Created Successfully";
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var course = await _courseService.GetCourseByIdAsync(id);
            return View(course);
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var course = await _courseService.GetCourseByIdAsync(id);
            return View(course);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Course model)
        {
            if (id != model.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                await _courseService.UpdateCourseAsync(id, model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var teacher = await _courseService.GetCourseByIdAsync(id);
            return View(teacher);
        }
        [HttpPost("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id, Course model)
        {
            var teacher = await _courseService.GetCourseByIdAsync(id);
            if (teacher == null)
                return NotFound();


            await _courseService.DeleteCourseAsync(id);
            return RedirectToAction("Index");

            return View(teacher);
        }
    }
}

MyFirstMvcApp/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyFirstMvcApp.Model;

namespace MyFirstMvcApp.Controllers
{
    public class TeacherController : Controller
    {
        //private readonly ILogger<TeacherController> _logger;
        private readonly StudentDbContext _context;
        public TeacherController(StudentDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            List<Teacher> teachers = new List<Teacher>();
            teachers = await _context.Teacher.ToListAsync();
            return View(teachers);
        }

        [HttpGet]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create()
        {
            var teacher = new Teacher() { Name = "" };
            return View(teacher);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Teacher model)
        {
            if (ModelState.IsValid)
            {
                _context.Teacher.Add(model);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var teacher = await _context.Teacher.FindAsync(id);
            return View(teacher);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Teacher model)
        {
            if (id != model.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                _context.Teacher.Update(model);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var teacher = await _context.Teacher.FindAsync(id);
            return View(teacher);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id,Teacher model)
        {
            var teacher = await _context.Teacher.FindAsync(id);
            if (teacher == null)
                return NotFound();

            
                _context.Teacher.Remove(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            
            return View(teacher);
        }
        [Route("{lang}/Teacher/Message/{text}")]
        public IActionResult Test(string lang, string text)
        {
            switch (lang)
            {
                case "np":
                    text = "Nepali text";
                    break;

                default:
                    text = "English text";
                    break;
            }
            return Json(text);
        }
    }
}

MyFirstMvcApp/Views/Shared/_FooterPartial.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - MyFirstMvcApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

MyFirstMvcApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFirstMvcApp</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyFirstMvcApp.styles.css" asp-append-version="true" />
</head>
<body>
    <partial name="_NavbarPartial" />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @Html.Partial("_FooterPartial")
   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyFirstMvcApp/Views/Shared/_NavbarPartial.cshtml
@{
    var user = Context.Session.GetString("UserName")??"Guest";
}
<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyFirstMvcApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Index">Teacher</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Course</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            @user
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>